made ul safer

diff --git a/ul b/ul
--- a/ul
+++ b/ul
@@ -1,11 +1,12 @@
 #!/bin/bash
 
+
 function error() {
 	echo "ERROR: $*" 1>&2
 	exit 1
 }
 
-if [ "$1" == "--help" ]; then
+if [[ -z "$1" ]] || [[ "$1" == "--help" ]]; then
 	echo -e "Usage=\tul --help
 \tul getUlRoot
 \tul getPropertiesFile
@@ -35,43 +36,57 @@ fi
 
 if [ "$1" == "getUlRoot" ]; then
 	[ ! "$2" == "-q" ] && [ ! -f "$HOME"/.ulroot ] && error "ulroot unset"
-	x=$(cat "$HOME"/.ulroot)
-	[ ! "$2" == "-q" ] && [ ! -d "$x" ] && error "ulroot directory not found"
-	echo "$x"
+	ulroot=$(cat "$HOME"/.ulroot)
+	[ ! "$2" == "-q" ] && [ ! -d "$ulroot" ] && error "'$ulroot' directory not found"
+	echo "$ulroot"
 fi
 
 if [ "$1" == "getPropertiesFile" ]; then
 	propsfile=$(. $0 getUlRoot)/properties
-	[ "$?" == 1 ] && exit 1
-	[ ! "$2" == "-q" ] && [ ! -f "$propsfile" ] && error "propsfile not found unset"
+	[ ! "$2" == "-q" ] && [ ! -f "$propsfile" ] && error "'$propsfile' not found"
 	echo "$propsfile"
 fi
 
 if [ "$1" == "setProperty" ]; then
+	if [ -z "$3" ]; then
+		error 'setProperty missing argument 3'
+	fi
 	propsfile=$(. $0 getPropertiesFile)
-	sed "/$2=*/d" -i $propsfile
-	echo "$2=$3" >> $propsfile
+	sed "/$2=/d" -i "$propsfile"
+	echo "$2=$3" >> "$propsfile"
 fi
 
 if [ "$1" == "getProperty" ]; then
-	propsfile=$(. $0 getPropertiesFile)
-	grep "$2=" $propsfile | sed "s/$2=//g"
+	if [ -z "$2" ]; then
+		error 'getProperty missing argument 2'
+	fi
+	propsfile="$(. $0 getPropertiesFile)"
+	grep "$2=" "$propsfile" | sed "s/$2=//g"
 fi
 
 if [ "$1" == "getProperties" ]; then
-	cat $(. $0 getPropertiesFile)
+	cat "$(. $0 getPropertiesFile)"
 fi
 
 if [ "$1" == "getServersDir" ]; then
-	echo "$(. $0 getUlRoot)/servers"
+	serversdir="$(. $0 getUlRoot)/servers"
+	[ ! "$2" == "-q" ] && [ ! -d "$serversdir" ] && error "'$serversdir' not found"
+	echo "$serversdir"
 fi
 
 if [ "$1" == "getConfsDir" ]; then
-	echo "$(. $0 getUlRoot)/confs"
+	confsdir="$(. $0 getUlRoot)/confs"
+	[ ! "$2" == "-q" ] && [ ! -d "$confsdir" ] && error "'$confsdir' not found"
+	echo "$confsdir"
 fi
 
 if [ "$1" == "getConfDir" ]; then
-	echo "$(. $0 getConfsDir)/$2"
+	if [ -z "$2" ]; then
+		error 'getConfDir missing argument 2'
+	fi
+	confdir="$(. $0 getConfsDir)/$2"
+	[ ! "$3" == "-q" ] && [ ! -d "$confdir" ] && error "'$confdir' not found"
+	echo "$confdir"
 fi
 
 if [ "$1" == "getLoadedConfPath" ]; then
@@ -79,12 +94,15 @@ if [ "$1" == "getLoadedConfPath" ]; then
 fi
 
 if [ "$1" == "loadConf" ]; then
-	initpath=$(. $0 getConfInit $2)
+	if [ -z "$2" ]; then
+		error 'loadConf missing argument 2'
+	fi
+	initpath="$(. $0 getConfInit "$2" "-q")"
 	if [ -f "$initpath" ]; then
 		chmod +x "$initpath"
 		"$initpath"
 	fi
-	. $0 setProperty loadedConf $2
+	. $0 setProperty loadedConf "$2"
 	sympath="$(. $0 getUlRoot)/loadedConf"
 	if [ -d "$sympath" ]; then
 		rm "$sympath"
@@ -93,18 +111,29 @@ if [ "$1" == "loadConf" ]; then
 fi
 
 if [ "$1" == "getConfInit" ]; then
-	echo $(. $0 getConfDir $2)/init
+	if [ -z "$2" ]; then
+		error 'getConfInit missing argument 2'
+	fi
+	initpath="$(. $0 getConfDir $2 "-q")/init"
+	[ ! "$3" == "-q" ] && [ ! -f "$initpath" ] && error "'$initpath' not found"
+	echo "$initpath"
 fi
 
 if [ "$1" == "createConf" ]; then
+	if [ -z "$2" ]; then
+		error 'createConf missing argument 2'
+	fi
 	if [ ! "$(. $0 doesConfExist $2)" == "true" ]; then
-		confdir="$(. $0 getConfDir $2)"
+		confdir="$(. $0 getConfDir $2 "-q")"
 		mkdir "$confdir"
 	fi
 fi
 
 if [ "$1" == "deleteConf" ]; then
-	if [[ ! "$(. $0 doesConfExist $2)" == "true" ]]; then
+	if [ -z "$2" ]; then
+		error 'deleteConf missing argument 2'
+	fi
+	if [[ ! "$(. $0 doesConfExist "$2")" == "true" ]]; then
 		if [ ! "$3" == "-q" ]; then
 			echo "conf $2 doesn't exist"
 		fi
@@ -121,7 +150,10 @@ if [ "$1" == "createDefaultConf" ]; then
 fi
 
 if [ "$1" == "doesConfExist" ]; then
-	if [ -d $(. $0 getConfDir $2) ]; then
+	if [ -z "$2" ]; then
+		error 'doesConfExist missing argument 2'
+	fi
+	if [ -d $(. $0 getConfDir "$2" '-q') ]; then
 		echo true
 	else
 		echo false
@@ -135,7 +167,7 @@ fi
 
 if [ "$1" == "cpConf" ]; then
 	if [ -z "$3" ]; then
-		error "cpConf: wrong amount of arguments"
+		error 'cpConf missing argument 3'
 	fi
 
 	if [[ $2 == *:* ]]; then
@@ -150,7 +182,9 @@ if [ "$1" == "cpConf" ]; then
 			for file in $files
 			do
 				filetarget="$(sed 's/confs\/'"$confname"'\///g' <<< "$file")"
-				curl -s "$serverpath/$file" -o "$(. $0 getConfDir $3)/$filetarget"
+				x=$(curl -s "$serverpath/$file" -o "$(. $0 getConfDir $3)/$filetarget")
+				[[ ! $? == 0 ]] && error 'cpConf: curl failed'
+				echo "$x"
 			done
 		fi
 	else
@@ -166,21 +200,30 @@ if [ "$1" == "cpConf" ]; then
 fi
 
 if [ "$1" == "addServer" ]; then
+	if [ -z "$3" ]; then
+		error "addServer missing argument 3"
+	fi
 	echo "$3" > "$(. $0 getServersDir)/$2"
 fi
 
 if [ "$1" == "deleteServer" ]; then
+	if [ -z "$2" ]; then
+		error "deleteServer missing argument 2"
+	fi
 	rm "$(. $0 getServersDir)/$2"
 fi
 
 if [ "$1" == "listServers" ]; then
-	for file in $(ls "$(. $0 getServersDir)/$2")
+	for file in $(ls "$(. $0 getServersDir)")
 	do
 		echo $file=$(cat $(. $0 getServersDir)/$file)
 	done
 fi
 
 if [ "$1" == "getServerURL" ]; then
+	if [ -z "$2" ]; then
+		error "getServerURL missing argument 2"
+	fi
 	if [[ $2 == *:* ]]; then
 		set $2 $(sed 's/:.*//g' <<< $2)
 	fi
@@ -202,14 +245,23 @@ if [ "$1" == "getServerURL" ]; then
 fi
 
 if [ "$1" == "getServerConfURL" ]; then
+	if [ -z "$2" ]; then
+		error "getServerConfURL missing argument 2"
+	fi
+
 	server="$(. $0 getServerURL "$(sed 's/:.*//g' <<< "$2")")"
 	confname="$(sed 's/.*://g' <<< "$2")"
 	echo "$server/confs/$confname"
 fi
 
 if [ "$1" == "getServerConfFiles" ]; then
+	if [ -z "$2" ]; then
+		error "getServerConfFiles missing argument 2"
+	fi
 	url="$(. $0 getServerURL "$2")"
 	confname="$(sed 's/.*://g' <<< "$2")"
 	path="$url/index.php?cmd=getFiles&conf=$confname"
-	echo "$(curl -s "$path")"
+	x="$(curl -s "$path")"
+	[[ ! $? == 0 ]] && error 'getServerConfFiles: curl failed'
+	echo "$x"
 fi
